---

- name: Create shell user
  user: name="{{ deploy_user }}"
        shell=/bin/bash groups="{{ httpd_user }}"
        append=yes
        generate_ssh_key=yes

- name: Install authorised users' public SSH keys
  authorized_key: user="{{ deploy_user }}"
                  key="https://code.siftware.com/{{ item }}.keys"
                  state=present
  with_items: "{{ ssh_users }}"

- name: Install build servers' public SSH key
  authorized_key: user="{{ deploy_user }}"
                  key="{{ item }}"
                  state=present
  with_file:
    - files/jenkins
  when: deploy_user_add_jenkins_ssh_key

- name: Install additional public SSH keys
  authorized_key: user="{{ deploy_user }}"
                  key="{{ item }}"
                  state=present
  with_items: "{{ deploy_user_additional_ssh_keys }}"
